### ISSUE TITLE
Do specs and Java standard library respect each other?

### ISSUE THREAD

**Issue by satbekmyrza** [OpenJML/Specs#25]
I have two questions:
- Do the specs and the Java standard library source code respect each other? 
- If yes, how was it verified (manually, automatically)?

Thanks

**Comment by leavens** [comment]
Hi Satbek,

I don't believe that we have formally verified that all the code in the JDK respects the specifications of the parts of the JDK that have been specified in a formal way.


        Regards,

        Gary T. Leavens
        329 L3Harris Center
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32816-2362 USA
        http://www.cs.ucf.edu/~leavens phone: +1-407-823-4758
        ***@***.******@***.***>

From: Satbek Abdyldayev ***@***.***>
Sent: Monday, January 30, 2023 2:58 AM
To: OpenJML/Specs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [OpenJML/Specs] Do specs and Java standard library respect each other? (Issue #25)


I have two questions:

  *   Do the specs and the Java standard library source code respect each other?
  *   If yes, how was it verified (manually, automatically)?

Thanks

-
