### ISSUE TITLE
Specification for java.nio.ByteBuffer.put(byte[]) appears to contradict Javadoc

### ISSUE THREAD

**Issue by slyubomirsky** [OpenJML/Specs#4]
The specification for put(byte[]) contains the following lines:

```
    //@   old int moved = Math.min(buf.length, limit - position);
    //@   assignable this.position, this.hb[position .. (position + (moved -1))];
    //@   ensures \fresh(\result);
    //@   ensures this.position == \old(this.position) + moved;
    //@   ensures (\forall int i; 0<=i && i<moved; buf[i] == hb[i+\old(position)]); // FIXME - check that this forall will reason correctly
```

The Javadoc states, "This method transfers the entire content of the given source byte array into this buffer. An invocation of this method of the form dst.put(a) behaves in exactly the same way as the invocation dst.put(a, 0, a.length)." This suggests that the method should always move all of the bytes from the argument into the ByteBuffer, not simply merely as many as would fit. I.e., `moved` should be exactly `buf.length` and there should be a `BufferOverflowException` if there is not enough space.

**Comment by davidcok** [comment]
Resolved with fixes to ByteBuffer specs
